In [1]:
    # !pip install paddleclas

In [1]:
import os
import cv2
from paddleocr import PPStructure,draw_structure_result,save_structure_res

table_engine = PPStructure(show_log=True, image_orientation=True)

save_folder = './output'
img_path = '/home/shivam/Documents/Github/Text-Extractor/image_processing/rotated.jpg'
img = cv2.imread(img_path)
result = table_engine(img)
save_structure_res(result, save_folder,os.path.basename(img_path).split('.')[0])

for line in result:
    line.pop('img')
    print(line)

from PIL import Image

font_path = '/home/shivam/Documents/Github/PaddleOCR/doc/fonts/simfang.ttf' # PaddleOCR下提供字体包
image = Image.open(img_path).convert('RGB')
im_show = draw_structure_result(image, result,font_path=font_path)
im_show = Image.fromarray(im_show)
im_show.save('result.jpg')

[2023/10/13 14:38:26] ppocr DEBUG: Namespace(alpha=1.0, alphacolor=(255, 255, 255), benchmark=False, beta=1.0, binarize=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir=None, cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/shivam/.paddleocr/whl/det/ch/ch_PP-OCRv4_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mode='fast', e2e_pgnet_score_thresh=0.5, e2e_pgnet_valid_set='

2023-10-13 14:38:26 INFO: Loading faiss with AVX2 support.
2023-10-13 14:38:26 INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-10-13 14:38:26 INFO: Loading faiss.
2023-10-13 14:38:26 INFO: Successfully loaded faiss.


[2023/10/13 14:38:26] ppcls WARNING: The current running environment does not support the use of GPU. CPU has been used instead.
[2023/10/13 14:38:28] ppocr DEBUG: dt_boxes num : 45, elapsed : 0.3112039566040039
[2023/10/13 14:38:34] ppocr DEBUG: rec_res num  : 45, elapsed : 6.189753293991089
[2023/10/13 14:38:36] ppocr DEBUG: dt_boxes num : 45, elapse : 0.3242208957672119
[2023/10/13 14:38:42] ppocr DEBUG: rec_res num  : 45, elapse : 5.669423580169678
{'type': 'figure', 'bbox': [1, 37, 2904, 857], 'res': [{'text': 'Sr. No.', 'confidence': 0.9407315254211426, 'text_region': [[117.0, 72.0], [295.0, 79.0], [293.0, 137.0], [115.0, 129.0]]}, {'text': 'Grade', 'confidence': 0.9905804395675659, 'text_region': [[2559.0, 66.0], [2732.0, 66.0], [2732.0, 123.0], [2559.0, 123.0]]}, {'text': 'Roll No.', 'confidence': 0.9969607591629028, 'text_region': [[392.0, 78.0], [603.0, 86.0], [601.0, 150.0], [390.0, 142.0]]}, {'text': 'Name', 'confidence': 0.9891712069511414, 'text_region': [[983.0, 91.0], [

In [3]:
from paddleocr import PaddleOCR, draw_ocr

In [4]:
ocr = PaddleOCR(lang='en')
image_path = '/home/shivam/Documents/Github/Text-Extractor/image_processing/rotated.jpg'
image_cv = cv2.imread(image_path)
image_height = image_cv.shape[0]
image_width = image_cv.shape[1]
output = ocr.ocr(image_path)[0]

[2023/10/13 14:39:10] ppocr DEBUG: Namespace(alpha=1.0, alphacolor=(255, 255, 255), benchmark=False, beta=1.0, binarize=False, cls_batch_num=6, cls_image_shape='3, 48, 192', cls_model_dir='/home/shivam/.paddleocr/whl/cls/ch_ppocr_mobile_v2.0_cls_infer', cls_thresh=0.9, cpu_threads=10, crop_res_save_dir='./output', det=True, det_algorithm='DB', det_box_type='quad', det_db_box_thresh=0.6, det_db_score_mode='fast', det_db_thresh=0.3, det_db_unclip_ratio=1.5, det_east_cover_thresh=0.1, det_east_nms_thresh=0.2, det_east_score_thresh=0.8, det_limit_side_len=960, det_limit_type='max', det_model_dir='/home/shivam/.paddleocr/whl/det/en/en_PP-OCRv3_det_infer', det_pse_box_thresh=0.85, det_pse_min_area=16, det_pse_scale=1, det_pse_thresh=0, det_sast_nms_thresh=0.2, det_sast_score_thresh=0.5, draw_img_save_dir='./inference_results', drop_score=0.5, e2e_algorithm='PGNet', e2e_char_dict_path='./ppocr/utils/ic15_dict.txt', e2e_limit_side_len=768, e2e_limit_type='max', e2e_model_dir=None, e2e_pgnet_mo

In [5]:
from pprint import pprint
pprint(output)

[[[[115.0, 75.0], [297.0, 75.0], [297.0, 138.0], [115.0, 138.0]],
  ('Sr.No.', 0.9259076118469238)],
 [[[2559.0, 69.0], [2731.0, 69.0], [2731.0, 120.0], [2559.0, 120.0]],
  ('Grade', 0.9982072114944458)],
 [[[395.0, 83.0], [603.0, 90.0], [601.0, 144.0], [393.0, 137.0]],
  ('Roll No.', 0.9687527418136597)],
 [[[1831.0, 84.0], [2064.0, 77.0], [2066.0, 131.0], [1833.0, 138.0]],
  ('Email Id', 0.9764333963394165)],
 [[[978.0, 99.0], [1142.0, 99.0], [1142.0, 152.0], [978.0, 152.0]],
  ('Name', 0.9988957643508911)],
 [[[2571.0, 144.0], [2688.0, 162.0], [2677.0, 236.0], [2559.0, 218.0]],
  ('41', 0.5651257038116455)],
 [[[176.0, 179.0], [218.0, 179.0], [218.0, 224.0], [176.0, 224.0]],
  ('1', 0.9952693581581116)],
 [[[346.0, 170.0], [627.0, 180.0], [626.0, 231.0], [345.0, 221.0]],
  ('2110993771', 0.9986019134521484)],
 [[[664.0, 179.0], [957.0, 186.0], [956.0, 240.0], [663.0, 233.0]],
  ('Baashi Nazir', 0.9877542853355408)],
 [[[1444.0, 183.0], [2201.0, 170.0], [2202.0, 221.0], [1445.0, 233.

## OCR FINISHED

## Ignore after this

In [6]:
boxes = [line[0] for line in output]
texts = [line[1][0] for line in output]
probabilities = [line[1][1] for line in output]

In [7]:
image_boxes = image_cv.copy()

In [8]:
for box,text in zip(boxes,texts):
  cv2.rectangle(image_boxes, (int(box[0][0]),int(box[0][1])), (int(box[2][0]),int(box[2][1])),(0,0,255),1)
  cv2.putText(image_boxes, text,(int(box[0][0]),int(box[0][1])),cv2.FONT_HERSHEY_SIMPLEX,1,(222,0,0),1)

In [9]:
cv2.imwrite('detections.jpg', image_boxes)

True

In [10]:
im = image_cv.copy()

In [11]:
horiz_boxes = []
vert_boxes = []

for box in boxes:
  x_h, x_v = 0,int(box[0][0])
  y_h, y_v = int(box[0][1]),0
  width_h,width_v = image_width, int(box[2][0]-box[0][0])
  height_h,height_v = int(box[2][1]-box[0][1]),image_height

  horiz_boxes.append([x_h,y_h,x_h+width_h,y_h+height_h])
  vert_boxes.append([x_v,y_v,x_v+width_v,y_v+height_v])

  cv2.rectangle(im,(x_h,y_h), (x_h+width_h,y_h+height_h),(0,0,255),1)
  cv2.rectangle(im,(x_v,y_v), (x_v+width_v,y_v+height_v),(0,255,0),1)
  

In [12]:
cv2.imwrite('horiz_vert.jpg',im)

True

In [13]:
# !pip install tensorflow

In [14]:
import tensorflow as tf
import numpy as np

2023-10-13 14:39:19.231150: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-13 14:39:20.028030: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [15]:
horiz_out = tf.image.non_max_suppression(
    horiz_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

2023-10-13 14:39:21.513122: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected


In [16]:
horiz_lines = np.sort(np.array(horiz_out))
print(horiz_lines)

[ 4  7 12 17 21 25 30 33 34 40]


In [17]:
im_nms = image_cv.copy()

In [18]:
for val in horiz_lines:
  cv2.rectangle(im_nms, (int(horiz_boxes[val][0]),int(horiz_boxes[val][1])), (int(horiz_boxes[val][2]),int(horiz_boxes[val][3])),(0,0,255),1)

In [19]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [20]:
vert_out = tf.image.non_max_suppression(
    vert_boxes,
    probabilities,
    max_output_size = 1000,
    iou_threshold=0.1,
    score_threshold=float('-inf'),
    name=None
)

In [21]:
print(vert_out)

tf.Tensor([21 20  4 42  1 24], shape=(6,), dtype=int32)


In [22]:
vert_lines = np.sort(np.array(vert_out))
print(vert_lines)

[ 1  4 20 21 24 42]


In [23]:
for val in vert_lines:
  cv2.rectangle(im_nms, (int(vert_boxes[val][0]),int(vert_boxes[val][1])), (int(vert_boxes[val][2]),int(vert_boxes[val][3])),(255,0,0),1)
  

In [24]:
cv2.imwrite('im_nms.jpg',im_nms)

True

In [25]:


out_array = [["" for i in range(len(vert_lines))] for j in range(len(horiz_lines))]
print(np.array(out_array).shape)
print(out_array)

(10, 6)
[['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', ''], ['', '', '', '', '', '']]


In [26]:

unordered_boxes = []

for i in vert_lines:
  print(vert_boxes[i])
  unordered_boxes.append(vert_boxes[i][0])

[2559, 0, 2731, 861]
[978, 0, 1142, 861]
[142, 0, 200, 861]
[327, 0, 609, 861]
[1435, 0, 2223, 861]
[621, 0, 733, 861]


In [27]:
ordered_boxes = np.argsort(unordered_boxes)
print(ordered_boxes)

[2 3 5 1 4 0]


In [28]:
def intersection(box_1, box_2):
  return [box_2[0], box_1[1],box_2[2], box_1[3]]

In [29]:
def iou(box_1, box_2):

  x_1 = max(box_1[0], box_2[0])
  y_1 = max(box_1[1], box_2[1])
  x_2 = min(box_1[2], box_2[2])
  y_2 = min(box_1[3], box_2[3])

  inter = abs(max((x_2 - x_1, 0)) * max((y_2 - y_1), 0))
  if inter == 0:
      return 0
      
  box_1_area = abs((box_1[2] - box_1[0]) * (box_1[3] - box_1[1]))
  box_2_area = abs((box_2[2] - box_2[0]) * (box_2[3] - box_2[1]))
  
  return inter / float(box_1_area + box_2_area - inter)

In [30]:
for i in range(len(horiz_lines)):
  for j in range(len(vert_lines)):
    resultant = intersection(horiz_boxes[horiz_lines[i]], vert_boxes[vert_lines[ordered_boxes[j]]] )

    for b in range(len(boxes)):
      the_box = [boxes[b][0][0],boxes[b][0][1],boxes[b][2][0],boxes[b][2][1]]
      if(iou(resultant,the_box)>0.1):
        out_array[i][j] = texts[b]

In [31]:
out_array=np.array(out_array)

In [32]:
out_array

array([['Sr.No.', 'Roll No.', '', 'Name', 'Email Id', 'Grade'],
       ['1', '2110993771', 'Baashi Nazir', '',
        'baashi3771.be21@chitkara.edu.in', '41'],
       ['2', '2110993795', 'Hitakshi', '',
        'hitakshi3795.be21@chitkara.edu.in', 'S3'],
       ['3', '2110993811', 'Mehakpreet', '',
        'mehakpreet3811.be21@chitkara.edu.in', '64'],
       ['4', '2110993832', 'Shivam Pandey', '',
        'shivam3832.be21@chitkara.edu.in', '9'],
       ['', '2110993839', 'SOHIL DHIMAN', 'SOHIL DHIMAN',
        'sohil3839.be21@chitkara.edu.in', '7'],
       ['', '2110993852', 'Vrinda Vritti', '',
        'vrinda3852.be21@chitkara.edu.in', ''],
       ['', '', '', '', '', ''],
       ['7', '2110993858', 'ADVITIYA BHARTI GUPTA',
        'ADVITIYA BHARTI GUPTA', 'advitiya3858.be21@chitkara.edu.in',
        '2'],
       ['8', '2110993876', 'Jatin', '', 'jatin3876.be21@chitkara.edu.in',
        '9']], dtype='<U35')

In [33]:
# Specify the file path
csv_file_path = 'output.csv'

# Save the array to a CSV file
np.savetxt(csv_file_path, out_array, delimiter=',', fmt='%s')

print(f'The array has been saved to {csv_file_path}.')

The array has been saved to output.csv.
